language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run
    - ./vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
